name: majeat
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  uuid: ^4.4.0


  cupertino_icons: ^1.0.6
  google_fonts:
  provider: ^6.1.2
  go_router: ^14.1.4
  curved_navigation_bar: ^1.0.3
  tuple: ^2.0.2
  flutter_tawk: ^0.1.0
  flutter_native_splash: ^2.4.0
  flutter_rating_bar: ^4.0.1
  intl: ^0.19.0
  equatable: ^2.0.5
  logger: ^2.3.0
  dartz: ^0.10.1
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter_native_splash:
  image: assets/splashScreen.png
  color: "#f9f9f9"
 
flutter:

 
  uses-material-design: true

  assets:

   - assets/
   - assets/images/background.png
   - assets/images/video.png
   - assets/data/user_profiles.json 

 