// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVxuzm1vJtOc1cJxY8LBo6N9L8uJfLes0',
    appId: '1:1065236137131:web:d2788aa291a073fe37e3ee',
    messagingSenderId: '1065236137131',
    projectId: 'majeat-f7755',
    authDomain: 'majeat-f7755.firebaseapp.com',
    storageBucket: 'majeat-f7755.appspot.com',
    measurementId: 'G-8XD88QDYQJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBT_LMYwa4OSYX91FrNsQApJw6_EnYA654',
    appId: '1:1065236137131:android:ee884be8cba3912037e3ee',
    messagingSenderId: '1065236137131',
    projectId: 'majeat-f7755',
    storageBucket: 'majeat-f7755.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiu_KO9Ro8XyEFj1Pju9qffTRqOqSi2lE',
    appId: '1:1065236137131:ios:7da91c08c23b03fd37e3ee',
    messagingSenderId: '1065236137131',
    projectId: 'majeat-f7755',
    storageBucket: 'majeat-f7755.appspot.com',
    iosBundleId: 'com.example.majeat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiu_KO9Ro8XyEFj1Pju9qffTRqOqSi2lE',
    appId: '1:1065236137131:ios:7da91c08c23b03fd37e3ee',
    messagingSenderId: '1065236137131',
    projectId: 'majeat-f7755',
    storageBucket: 'majeat-f7755.appspot.com',
    iosBundleId: 'com.example.majeat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVxuzm1vJtOc1cJxY8LBo6N9L8uJfLes0',
    appId: '1:1065236137131:web:3d92fd5f9c0ed21437e3ee',
    messagingSenderId: '1065236137131',
    projectId: 'majeat-f7755',
    authDomain: 'majeat-f7755.firebaseapp.com',
    storageBucket: 'majeat-f7755.appspot.com',
    measurementId: 'G-78D4E0T29J',
  );
}
